/**
 * A figure whose image is a build asset rather than Tina media.
 *
 * This exists because of a production-only 404. A markdown image in a rich-text
 * body is Tina media by definition, so Tina rewrites its src to
 * assets.tina.io/<project>/<file> and expects the file on its CDN. That is right
 * for anything uploaded through the Tina editor, and wrong for anything the
 * build produces: public/phoenix.png is generated by tools/phoenix and committed
 * to the repo, so it has never existed on Tina's CDN and the rewritten URL was a
 * hard 404. Chrome then reported ERR_BLOCKED_BY_ORB, because S3 answers a 404
 * with text/html and Chrome refuses an HTML response to an image request.
 *
 * `src` is a plain string, not an `image` field, which is the entire point:
 * Tina does not touch string fields, so the path survives as written. The demo
 * video already worked for exactly this reason while the sprite sheet did not.
 *
 * Use this for anything under public/. Use a normal markdown image for anything
 * uploaded through the editor.
 */
import type { Template } from 'tinacms';

export const figureTemplate: Template = {
  name: 'Figure',
  label: 'Figure (build asset)',
  fields: [
    {
      name: 'src',
      label: 'Path',
      type: 'string',
      required: true,
      description:
        'A path under public/, such as /phoenix.png. For images uploaded here, use a normal markdown image instead.',
    },
    { name: 'alt', label: 'Alt text', type: 'string' },
    {
      name: 'caption',
      label: 'Caption',
      type: 'string',
      description: 'Supports markdown, so [links](https://example.com) work.',
      ui: { component: 'textarea' },
    },
  ],
};
