'use client';
import { iconSchema } from '@/tina/fields/icon';
import { Transition } from 'motion/react';
import Image from 'next/image';
import Link from 'next/link';
import type { Template } from 'tinacms';
import { tinaField } from 'tinacms/dist/react';
import { PageBlocksHero, PageBlocksHeroImage } from '../../tina/__generated__/types';
import { Icon } from '../icon';
import { Section, sectionBlockSchemaField } from '../layout/section';
import { AnimatedGroup } from '../motion-primitives/animated-group';
import { TextEffect } from '../motion-primitives/text-effect';
import { Button } from '../ui/button';
import HeroVideoDialog from '../ui/hero-video-dialog';
import { FadeInImage } from '../ui/fade-in-image';
const transitionVariants = {
  container: {
    visible: {
      transition: {
        staggerChildren: 0.05,
        delayChildren: 0.75,
      },
    },
  },
  item: {
    hidden: {
      opacity: 0,
      filter: 'blur(12px)',
      y: 12,
    },
    visible: {
      opacity: 1,
      filter: 'blur(0px)',
      y: 0,
      transition: {
        type: 'spring',
        bounce: 0.3,
        duration: 1.5,
      } as Transition,
    },
  },
};

export const Hero = ({ data }: { data: PageBlocksHero }) => {
  return (
    <Section background={data.background!} className='mx-auto flex min-h-[calc(100svh-5rem)] max-w-6xl flex-col items-center gap-10 lg:flex-row lg:gap-20'>
      <div className='w-full text-center lg:w-1/2 lg:text-left'>
        {data.headline && (
          <div data-tina-field={tinaField(data, 'headline')}>
            <TextEffect preset='fade-in-blur' speedSegment={0.3} as='h1' className='text-balance text-6xl md:text-7xl xl:text-[5.25rem]'>
              {data.headline!}
            </TextEffect>
          </div>
        )}
        {data.tagline && (
          <div data-tina-field={tinaField(data, 'tagline')}>
            <TextEffect per='line' preset='fade-in-blur' speedSegment={0.3} delay={0.5} as='p' className='mx-auto mt-8 max-w-2xl text-balance text-lg lg:mx-0'>
              {data.tagline!}
            </TextEffect>
          </div>
        )}

        <AnimatedGroup variants={transitionVariants} className='mx-auto mt-12 flex w-full max-w-xl flex-col items-stretch justify-center gap-3 md:flex-row lg:mx-0 lg:justify-start'>
          {data.actions &&
            data.actions.map((action) => (
              <div key={action!.label} data-tina-field={tinaField(action)} className='flex-1'>
                <Button asChild size='lg' variant={action!.type === 'link' ? 'ghost' : 'default'} className='w-full text-base'>
                  <Link href={action!.link!}>
                    {action?.icon && <Icon data={action?.icon} />}
                    <span className='text-nowrap'>{action!.label}</span>
                  </Link>
                </Button>
              </div>
            ))}
        </AnimatedGroup>
      </div>

      {data.image && (
        <AnimatedGroup variants={transitionVariants} className='w-full lg:w-1/2'>
          <div className='relative max-w-full overflow-hidden' data-tina-field={tinaField(data, 'image')}>
            <div className='relative mx-auto max-w-lg overflow-hidden lg:max-w-none'>
              <ImageBlock image={data.image} />
            </div>
          </div>
        </AnimatedGroup>
      )}
    </Section>
  );
};

const ImageBlock = ({ image }: { image: PageBlocksHeroImage }) => {
  // @ts-ignore - videoSrc will be generated by TinaCMS codegen after schema update
  if (image.videoSrc) {
    return (
      <div className='relative flex items-center justify-center'>
        {/* Aura Effect */}
        <div className='absolute inset-0 -z-10 bg-gradient-to-tr from-purple-500/30 via-blue-500/30 to-pink-500/30 blur-3xl' />

        <video
          className='z-2 aspect-square relative h-auto max-w-full object-cover [mask-image:radial-gradient(circle,black_60%,transparent_100%)]'
          autoPlay
          loop
          muted
          playsInline
          // @ts-ignore
          src={image.videoSrc}
        />
      </div>
    );
  }

  if (image.videoUrl) {
    let videoId = '';
    if (image.videoUrl) {
      const embedPrefix = '/embed/';
      const idx = image.videoUrl.indexOf(embedPrefix);
      if (idx !== -1) {
        videoId = image.videoUrl.substring(idx + embedPrefix.length).split('?')[0];
      }
    }
    const thumbnailSrc = image.src ? image.src! : videoId ? `https://i3.ytimg.com/vi/${videoId}/maxresdefault.jpg` : '';

    return <HeroVideoDialog videoSrc={image.videoUrl} thumbnailSrc={thumbnailSrc} thumbnailAlt='Hero Video' />;
  }

  if (image.src) {
    return (
      <FadeInImage
        className='z-2 border-border/50 aspect-15/8 relative h-auto max-w-full rounded-sm border'
        alt={image!.alt || ''}
        src={image!.src!}
        height={4000}
        width={3000}
        priority
      />
    );
  }
};

export const heroBlockSchema: Template = {
  name: 'hero',
  label: 'Hero',
  ui: {
    previewSrc: '/blocks/hero.png',
    defaultItem: {
      tagline: "Here's some text above the other text",
      headline: 'This Big Text is Totally Awesome',
      text: 'Phasellus scelerisque, libero eu finibus rutrum, risus risus accumsan libero, nec molestie urna dui a leo.',
    },
  },
  fields: [
    sectionBlockSchemaField as any,
    {
      type: 'string',
      label: 'Headline',
      name: 'headline',
    },
    {
      type: 'string',
      label: 'Tagline',
      name: 'tagline',
    },
    {
      label: 'Actions',
      name: 'actions',
      type: 'object',
      list: true,
      ui: {
        defaultItem: {
          label: 'Action Label',
          type: 'button',
          icon: {
            name: 'Tina',
            color: 'white',
            style: 'float',
          },
          link: '/',
        },
        itemProps: (item) => ({ label: item.label }),
      },
      fields: [
        {
          label: 'Label',
          name: 'label',
          type: 'string',
        },
        {
          label: 'Type',
          name: 'type',
          type: 'string',
          options: [
            { label: 'Button', value: 'button' },
            { label: 'Link', value: 'link' },
          ],
        },
        iconSchema as any,
        {
          label: 'Link',
          name: 'link',
          type: 'string',
        },
      ],
    },
    {
      type: 'object',
      label: 'Image',
      name: 'image',
      fields: [
        {
          name: 'src',
          label: 'Image Source',
          type: 'image',
        },
        {
          name: 'alt',
          label: 'Alt Text',
          type: 'string',
        },
        {
          name: 'videoUrl',
          label: 'YouTube Embed URL',
          type: 'string',
          description: 'If using a YouTube video, make sure to use the embed version of the video URL',
        },
        {
          name: 'videoSrc',
          label: 'Video Source (MP4/WebM)',
          type: 'image',
          description: 'Upload an MP4 or WebM video file. This will autoplay and loop.',
        },
      ],
    },
  ],
};
